name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
env:
  global_env: global
      
jobs:
  sys_info:
    runs-on: windows-latest
    env:
      local_env: job
      
    steps:
      - name: check tools
        run: g++ -v
        
  build:
    needs: [sys_info]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1

      - name: build
        run: cl /EHsc mix_naznach.cpp

      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: assignment_problem_git
          path: mix_naznach.exe
          retention-days: 1
