name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
env:
  global_env: global
      
jobs:
  sys_info:
    runs-on: windows-latest
    env:
      local_env: job

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: user
        run: uname
      - name: sysinfo
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
